CREATE TABLE `pray_2023` (
  `id` int(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `barcode` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '報到條碼',
  `name` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '姓名',
  `tel` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '電話',
  `sex` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '性別',
  `age` int(8) DEFAULT '0' COMMENT '年齡',
  `area` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '區域',
  `classarea` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '教室',
  `classroom` varchar(12) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '母班班別',
  `classroomid` varchar(12) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '母班班別代碼',
  `classother` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `group` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '義工大組別',
  `subgroup` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '義工小組別',
  `join` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '參與日',
  `join1` int(4) DEFAULT '0' COMMENT '參與日1',
  `join2` int(4) DEFAULT '0' COMMENT '參與日2',
  `join3` int(4) DEFAULT '0' COMMENT '參與日3',
  `join4` int(4) DEFAULT '0' COMMENT '參與日4',
  `join5` int(4) DEFAULT '0' COMMENT '參與日5',
  `join6` int(4) DEFAULT '0' COMMENT '參與日6',
  `join7` int(4) DEFAULT '0' COMMENT '參與日7',
  `join8` int(4) DEFAULT '0' COMMENT '參與日8',
  `join9` int(4) DEFAULT '0' COMMENT '參與日9',
  `joinx` int(4) DEFAULT '0' COMMENT '參與日x',
  `live` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住宿日',
  `live1` int(4) DEFAULT '0' COMMENT '住宿日1',
  `live2` int(4) DEFAULT '0' COMMENT '住宿日2',
  `live3` int(4) DEFAULT '0' COMMENT '住宿日3',
  `live4` int(4) DEFAULT '0' COMMENT '住宿日4',
  `live5` int(4) DEFAULT '0' COMMENT '住宿日5',
  `live6` int(4) DEFAULT '0' COMMENT '住宿日6',
  `live7` int(4) DEFAULT '0' COMMENT '住宿日7',
  `live8` int(4) DEFAULT '0' COMMENT '住宿日8',
  `live9` int(4) DEFAULT '0' COMMENT '住宿日9',
  `livex` int(4) DEFAULT '0' COMMENT '住宿日x',
  `livewhere` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住宿區',
  `liveroom` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住宿房',
  `type` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '義工類別',
  `notify` int(4) DEFAULT '0' COMMENT '通知單發放',
  `specialcase` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '身體特殊狀況',
  `request` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住宿特殊希求',
  `trafficgo` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '搭車去',
  `trafficback` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '搭車回',
  `pay` int(4) DEFAULT '0' COMMENT '已交車資',
  `trafficself` int(4) DEFAULT '0' COMMENT '自行往返',
  `joinclean` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '參與打掃日',
  `trafficclean` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '打掃搭車',
  `memo` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '備註',
  `applydate` date DEFAULT '1970-01-01' COMMENT '報名日期',
  `applyby` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '報名者',
  `checkin` int(8) DEFAULT '0' COMMENT '報到',
  `checkin1` int(4) DEFAULT '0' COMMENT '日1報到',
  `checkin2` int(4) DEFAULT '0' COMMENT '日2報到',
  `checkin3` int(4) DEFAULT '0' COMMENT '日3報到',
  `checkin4` int(4) DEFAULT '0' COMMENT '日4報到',
  `checkin5` int(4) DEFAULT '0' COMMENT '日5報到',
  `checkin6` int(4) DEFAULT '0' COMMENT '日6報到',
  `checkin7` int(4) DEFAULT '0' COMMENT '日7報到',
  `checkin8` int(4) DEFAULT '0' COMMENT '日8報到',
  `checkin9` int(4) DEFAULT '0' COMMENT '日9報到',
  `checkinx` int(4) DEFAULT '0' COMMENT '日x報到',
  `duplication` int(4) DEFAULT '0' COMMENT '重覆報名註記',
  `invalidate` int(4) DEFAULT '0' COMMENT '無效資料註記'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;